name: good_doctor
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Must have in all apps
  dio: ^5.1.1
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.1
  auto_route: ^7.1.0
  flutter_gen: ^5.3.1
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.3+2
  either_dart: ^0.4.0
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  animated_bottom_navigation_bar: ^1.1.0+1
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  hive: ^2.2.3

  #Firebase
  firebase_core: ^2.1.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.0.2
  flutter_local_notifications: ^14.0.0+1

  #Authenticator
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.1

  #Otp
  pin_code_fields: ^7.4.0

  fl_chart: ^0.62.0
  timeago: ^3.3.0
  lottie: ^2.2.0
  toggle_switch: ^2.0.1
  qr_flutter: ^4.0.0
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.0.0
  build_runner: ^2.2.0
  freezed: ^2.0.5
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.0
  json_serializable: ^6.3.1
  flutter_gen_runner: any
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
#  flutter_flavorizr: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/translations/

flutter_gen:
  output: lib/resources/
  line_length: 100

  assets:
    enabled: true
    # Assets.images.chip
    outputs:
      style: dot-delimiter

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
